### PR TITLE
first page change, to review with pacer for technique confirmation nbpm

### PR DESCRIPTION
**Pull request by Ivy4**

### CODE REVIEW

**Comment by bohmj** [comment]
- Line 4: style sheet link missing `rel="stylesheet"`

- Line 5: colorbox pages need to reference the key elements style sheet. (/css/key-elements-responsive.min.css) Note:  This style sheet is currently broken and I need to fix the broken image paths to map correctly to our server locations, so ignore styling issues of color box pop ups for now on staging.

- Line 51: meta description content should match the meta og:description tag content

- Line 63: virtual path to the left nav file of the original (/bullying/nbpm/nav.html)

- Line 72: currID variable needs to be set to the correct value from original (overview)

- Line 109: I had some invalid characters.  The Left Single Quote character should come across fine in a UTF-8 document without using the html entity for that character.  Check to make sure that the file is using utf-8 when you save, or could be getting converted by GIT? We may need to investigate that further if it continues to show up.

Everything else looks great as for converting to the bullying template. There are some image sizing issues with the bottom tables at mobile sizes, but that will show up in review.  and there is an alternative flexbox option for pages with thumbnail images and descriptions that can be utilized in the updated flex layouts template.  http://staging.pacer.org/templates/responsive-flex-layouts.asp

I'll upload the most recent template files and css files to this repo shortly.

**Comment by bohmj** [comment]
I did load this version to staging at the moment if you want to see how it looks. http://staging.pacer.org/bullying/nbpm/

**Comment by kblanfor** [comment]
Thanks @bohmj -- I'm going to update my stuff based on your feedback here and initiate a pull request once you've posted those updated templates.

**Comment by bohmj** [comment]
Template Update Pushed to master. Should not impact your current file as the change to the bullying template only fixes in issue with pages that have to show 4th level left navigation.

**Comment by kblanfor** [comment]
Thanks, @bohmj -- I'll pull those down.

**Pull request merged**
