### PR TITLE
Kblanfor

### PR DESCRIPTION
**Pull request by kblanfor**

### CODE REVIEW

**Comment by kblanfor** [comment]
@bohmj we have 3 open pull requests now -- if we could get these pages into the staging environment to identify any gaps in continuing to convert pages, that'd be helpful. Thanks!

**Comment by bohmj** [comment]
Thanks.  I have the syncing system set up and will be running it shortly.  I will update as each branch gets pushed.

**Comment by bohmj** [comment]
Question? - I think it would be more straight forward for me to merge all the pull requests into master and then run a sync to staging from the master branch.  Do you think there would be any issues merging these pull requests as they come up?  Not sure which workflow would be standard procedure with frequent pull requests.

**Comment by kblanfor** [comment]
If you approve and 'merge' the pull request to master, go ahead and do the syncing. The pull request process is more for our review and version control so merging to master to sync makes the most sense.

**Pull request merged**
